---
  name: Build Component

  on:
    push:
    pull_request:

  jobs:
    build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v5

        - name: Compile
          uses: esphome/build-action@v7
          with:
            yaml-file: .github/example_build_hcpbridge.yaml
